language: php

php:
  - 5.5.9
  - 5.5
  - 5.6
  - 7.0
  - hhvm

install:
  - composer install
  - touch .env
  - echo "APP_ENV=testing" > .env
  - echo "APP_DEBUG=true" >> .env
  - echo "APP_KEY=APP_KEY=12345678901234567890123456789012" >> .env
  - php artisan key:generate

script: vendor/bin/phpunit